// Regenerates assets.generated.ts from the repo's generated SVGs.
// Run after `npm run build` whenever gen.ts output changes:
//   node design-system/react/embed.mjs
// The React wrappers (Logo, Mark, Icon, Loader) embed these strings verbatim —
// never edit assets.generated.ts by hand.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const read = (rel) => readFileSync(join(root, rel), "utf8").trim();

const assets = {
  logoLight: "logo/overcast-logo-light.svg",
  logoDark: "logo/overcast-logo-dark.svg",
  markLight: "mark/mark-light.svg",
  markDark: "mark/mark-dark.svg",
  markMonoInk: "mark/mark-mono-ink.svg",
  markMonoWhite: "mark/mark-mono-white.svg",
  icon16: "icons/icon-16.svg",
  icon32: "icons/icon-32.svg",
  icon48: "icons/icon-48.svg",
  icon96: "icons/icon-96.svg",
  icon256: "icons/icon-256.svg",
  loader: "loading/overcast-loader.svg",
};

const banner =
  "// GENERATED by design-system/react/embed.mjs — do not edit.\n" +
  "// Source: the repo's generated SVG assets (logo/, mark/, icons/, loading/).\n";

const body = Object.entries(assets)
  .map(([name, rel]) => `export const ${name} = ${JSON.stringify(read(rel))};\n`)
  .join("");

writeFileSync(join(here, "assets.generated.ts"), banner + body);
console.log(`assets.generated.ts: ${Object.keys(assets).length} SVGs embedded`);
